services:
  - type: web
    name: dhstore-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: node dist/index.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dhstore-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: https://app.dhstore.rw
      - key: FORCE_HTTPS
        value: "true"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: no-reply@dhstore.rw

  - type: web
    name: dhstore-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://api.dhstore.rw

databases:
  - name: dhstore-postgres
    plan: free
