services:
  - type: web
    name: dhstore-backend
    env: python
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start" --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dhstore-db
          property: connectionString

  - type: web
    name: dhstore-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://dhstore-backend.onrender.com

databases:
  - name: dhstore-db
    databaseName: dhstore
    user: dhstore
