services:
  - type: web
    name: dhstore-backend
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://your-frontend-domain.com
      - key: FORCE_HTTPS
        value: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "no-reply@dhstore.rw"
